### ISSUE TITLE
Migrate from packed_simd to stdlib simd (aka portable simd)

### ISSUE THREAD

**Issue by SUPERCILEX** [dimforge/simba#33]
Packed simd stopped compiling a few days ago: https://github.com/rust-lang/packed_simd/issues/343. It should be replaced with portable simd: https://doc.rust-lang.org/std/simd/index.html

**Comment by bjorn3** [comment]
This issue is preventing rapier from working with cg_clif when simd-unstable is enabled: https://github.com/bjorn3/rustc_codegen_cranelift/issues/1361

**Comment by davemollen** [comment]
packed_simd stopped compiling because the platform_intrinsics feature has been removed. Maybe this makes the earlier request for replacement with portable simd relevant again.

See the issue at the packed_simd repository: https://github.com/rust-lang/packed_simd/issues/360

**Comment by ProfFan** [comment]
And https://github.com/rust-lang/portable-simd
