### ISSUE TITLE
Update Crates.io version

### ISSUE THREAD

**Issue by MickHarrigan** [dimforge/simba#50]
Making this issue to let the maintainers know that the version on github is not matching that of the version on [crates.io](https://crates.io/crates/simba). 

Hopefully this is just a quick update and can be fixed quite simply.

I found and referenced this [#274](https://github.com/janhohenheim/foxtrot/issues/274) as it is causing problems in a different area.

**Comment by MickHarrigan** [comment]
@sebcrozet Would you be able to update the crates.io version of this? It is not currently tracking the most up to date version there and still has the issues from [packed_simd v0.3.8](https://github.com/rust-lang/packed_simd) when compiling for nightly.

**Comment by sebcrozet** [comment]
A new version will be published today. However, I’m dropping support for `packed_simd` considering it is still broken with the latest nightly (it can be revived in the future by getting the code back from the git history).
